<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Easy Timebutler</title>
    <meta name="robots" content="noindex,nofollow" />
    <meta name="description" content="Easy Timebutler">
</head>
<body>

<h1>Easy Timebutler</h1>
<main>
    ...loading...
</main>

<script src="/app.js"></script>
</body>
</html>
